/*
 *
 * SignUp constants
 *
 */

export const DEFAULT_ACTION = 'app/SignUp/DEFAULT_ACTION';

export const DEFAULT_ACTION_REQUEST = 'app/SignUp/DEFAULT_ACTION_REQUEST';
export const DEFAULT_ACTION_SUCCESS = 'app/SignUp/DEFAULT_ACTION_SUCCESS';
export const DEFAULT_ACTION_FAILURE = 'app/SignUp/DEFAULT_ACTION_FAILURE';



export const REGISTER_REQUEST = 'app/Register/REGISTER_REQUEST';
export const REGISTER_REQUEST_SUCCESS = 'app/Register/REGISTER_REQUEST_SUCCESS';
export const REGISTER_REQUEST_FAILURE = 'app/Register/REGISTER_REQUEST_FAILURE';
